# Generated by Django 3.0.5 on 2020-04-15 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_auto_20200410_0133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='eye_image',
            field=models.ImageField(default='negative.jpg', upload_to='eye_images'),
        ),
    ]
